### PR TITLE
After audit changes other owner

### PR DESCRIPTION
**Pull request by gbalabasquer**

### CODE REVIEW

**Comment by gbalabasquer** [comment]
@NiklasKunkel @r001 very simple change discussed with Bartek and Rain about adding the possibility to set another owner to the offer. This would be useful if a proxy is creating the offer for you.

**Comment by r001** [comment]
It's fine with me.

**Comment by gbalabasquer** [comment]
> Allowing for the zero address to default to `msg.sender` will save roughly 3000 gas per call

hey, I'm not following you on this, what is exactly the proposal?

**Comment by BrendanChou** [comment]
Because (non-zero data bytes) cost more than (zeroed data bytes) in the call data, if you require users to start specifying their own addresses in the calldata, then this will cost additional gas

68 gas per byte of nonzero-data
4 gas per byte of zero-data

It would be nice if the zero address defaulted to `msg.sender`

**Comment by BrendanChou** [comment]
Ah okay thought these modified the existing functions rather than adding new ones

**Comment by gbalabasquer** [comment]
@NiklasKunkel I'm merging this, if you have any suggested change, we can do it in the branch. Anyway it is still a work in progress.

**Pull request merged**
