### PR TITLE
Migrate to dapple 0.8 / solidity 0.4.2

### PR DESCRIPTION
**Pull request by rainbeam**
Replaces #146.

### CODE REVIEW

**Comment by rainbeam** [comment]
@mhhf: any idea about this travis failure?

https://travis-ci.org/makerdao/maker-otc/builds/167595336#L1402

`Error: ENOENT: no such file or directory, open '/home/travis/build/makerdao/maker-otc/.dapple/.gitignore'`

Travis is using dapple with `npm install -g dapple`

**Comment by rainbeam** [comment]
I don't fully understand why initially the pr build fails and the push build passes but I think it's just travis weirdness. The pr build passes when restarted.

**Comment by rainbeam** [comment]
Looks like travis failure was at least partly due to the dyn ddos.

**Comment by rainbeam** [comment]
@jorisbontje: so the deployment was successful with all that you've pushed here?

I'm not sure why the tests are failing again.

```
$ if [ $TEST = "dapple" ]; then dapple test; fi
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open '/home/travis/build/makerdao/maker-otc/.dapple/.gitignore'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at State.initLocalDb (/home/travis/.nvm/versions/node/v6.8.1/lib/node_modules/dapple/node_modules/dapple-core/state.js:72:10)
    at nextTask (/home/travis/.nvm/versions/node/v6.8.1/lib/node_modules/dapple/node_modules/async/dist/async.js:5208:14)
    at /home/travis/.nvm/versions/node/v6.8.1/lib/node_modules/dapple/node_modules/async/dist/async.js:5202:13
    at apply (/home/travis/.nvm/versions/node/v6.8.1/lib/node_modules/dapple/node_modules/async/dist/async.js:41:25)
    at /home/travis/.nvm/versions/node/v6.8.1/lib/node_modules/dapple/node_modules/async/dist/async.js:76:12
    at /home/travis/.nvm/versions/node/v6.8.1/lib/node_modules/dapple/node_modules/async/dist/async.js:988:16
    at initGlobalState (/home/travis/.nvm/versions/node/v6.8.1/lib/node_modules/dapple/node_modules/dapple-core/state.js:41:7)
```

**Comment by jorisbontje** [comment]
@rainbeam dapple issue fixed in https://github.com/nexusdev/dapple-core/commit/df9fb9a09adde4f8cabd16d8f37bf70a4de17b0d ?

**Comment by rainbeam** [comment]
@jorisbontje: probably. Travis installs dapple from npm so maybe hasn't got that yet.

**Pull request merged**
