### PR TITLE
Some renaming and comments updates

### PR DESCRIPTION
**Pull request by godsflaw**
Just a work in progress for the code review.

### CODE REVIEW

**Comment by gbalabasquer** [comment]
Hmmm I think idea is to keep `^0.5.12` that is why we upgraded `dss` and we will do the same to the other packages

**Comment by godsflaw** [comment]
> Hmmm I think idea is to keep `^0.5.12` that is why we upgraded `dss` and we will do the same to the other packages

I thought we wanted to let it float in the code, but lock for deployments?  I locked it down here because this is about to be redeployed.  Let me know if this isn't what we want.

**Comment by gbalabasquer** [comment]
I'd just let it float, as we might even deploy `maker-otc` with solc 0.5.15 or 16 if gets added to dapptools soon.
We do not have FV for this, so restricting the version of solc feels a bit pointless here.

**Comment by godsflaw** [comment]
> I'd just let it float, as we might even deploy `maker-otc` with solc 0.5.15 or 16 if gets added to dapptools soon.
> We do not have FV for this, so restricting the version of solc feels a bit pointless here.

The only reason I can think of to lock the version, other than FV, is that certain `solc` versions have compiler bugs.  So if we lock to the version, one always knows what `solc` was used to compile for that deployed version and if it is now vulnerable to any bugs, and conversely that bugs introduced in newer `solc` version don't impact that deployment.

This version locking is suggested in `SWC-103` too: https://swcregistry.io/docs/SWC-103

For this reason, I do think we should lock to a version on deploy, then change back to a floating version pragma.

**Comment by gbalabasquer** [comment]
Yeah I get the point. I still think that you can make sure with which version was compiled just checking the verified source in Etherscan. Even maybe putting a note in the README with solc version and contract address. Fixing the pragma doesn't fix the bytecode as you also have the optimization option to choose.
Anyway, if the majority prefers to keep it locked for deploying, I'm fine as well.

**Comment by gbalabasquer** [comment]
I'm closing this PR as the base won't be happening either. I've cherry pick some of them for: https://github.com/makerdao/maker-otc/pull/190

**Pull request closed without merging**
