### PR TITLE
Non-MAR tokens (WIP)

### LINKED ISSUE #7: EIP20 / non-MAR tokens
An opportunity to consider a union type like:

```
struct token_desc {
     bool is_symbol;
     bytes20 symbol_or_address;
}

function extractToken(token_desc t) returns (address) {
    if( t.is_symbol ) {
        return _registry.getToken(bytes32(t.symbol_or_address));
    } else {
        return address(t.symbol_or_address);
}
```

A more future-proof alternative which efficiently uses 1 word (optimal use of mapping value space):

```
struct token_desc {
    bytes12 metadata;
    bytes20 address_or_symbol;
}
```

### PR DESCRIPTION
**Pull request by jorisbontje**
Closes #7 

TODO:
* [ ] generic code cleanup; remove unused packages?
* [ ] deployment to Mainnet

### CODE REVIEW

**Comment by rainbeam** [comment]
Do you envisage much more change here? I can rebase #92 on top of it.

**Comment by jorisbontje** [comment]
I don't expect the market contract to change much anymore. However the UI and wrappers do need to be updated. The tests could be further refactored to remove MAR compatibility; however I haven't done so as to ensure test suite compatibility.

**Comment by rainbeam** [comment]
Great.

Regarding tests: I think moving away from maker-user is as simple as using `Tester` from `dapple/test` and implementing the `doApprove` method. See how I've done it in [token-auction][tester-example].

[tester-example]: https://github.com/rainbeam/token-auction/blob/2a5416a2e0d6436c39b6d388c0499d25892a6807/contracts/splitting_auction_test.sol#L17-L38

So here it's probably just this:

```
contract MarketTester is Tester {
    function doApprove(address spender, uint value, ERC20 token) {
        token.approve(spender, value);
    }
```

**Comment by jorisbontje** [comment]
Remove DGD support / flexible precision as it isn't required for the first EIP20 market release

**Comment by jorisbontje** [comment]
Merged to `erc20` branch.

**Pull request closed without merging**
