### PR TITLE
Use travis

### PR DESCRIPTION
**Pull request by rainbeam**
Simple travis set up. Addresses #10.

Todo:

- [x] solc js failure [fixed with latest npm dapple]
- [x] can we speed up build with caching / docker image? (yes, see #31)

### CODE REVIEW

**Comment by rainbeam** [comment]
@jorisbontje here is work in progress. Can see travis build status on my repo: https://travis-ci.org/rainbeam/maker-otc

Can you switch on travis on this repo?

**Comment by rainbeam** [comment]
Currently have a failure of solc js with `TypeError: Converting circular structure to JSON`. Not sure what causes this. I get the same problem in a docker build but not on my machine.

**Comment by ryepdx** [comment]
I'll take a look at the circular structure error and get back to you.

**Comment by ryepdx** [comment]
Can't seem to reproduce the circular structure error. solc-js also seems to have trouble with the `new bytes` statement in dappsys' `gov/easy_multisig_test.sol` file. Are you sure it's using solc-js? Do you have solc installed?

**Comment by rainbeam** [comment]
The failure is in travis, which only has solc-js via the dapple install. You can see the full error message in the travis build output, linked above.

I've just reproduced again from a vanilla ubuntu:15.10 docker container with:

```bash
apt update
apt install -y curl
curl -sL https://deb.nodesource.com/setup_5.x | bash
apt install -y nodejs git build-essential python
npm install --global dapple
cd $HOME
echo -e 'environments:\n  evm: default' > .dapplerc
git clone https://github.com/makerdao/maker-otc
cd maker-otc/
git submodule update --init --recursive
dapple test
```

**Comment by ryepdx** [comment]
This looks like this is due to the difference between what's on NPM and what's on Github. Should be resolved after Nikolai pushes another release.

**Comment by nmushegian** [comment]
dapple 0.7.1 published to npm

**Comment by jorisbontje** [comment]
The Docker script by @rainbeam passes with the newly released dapple 0.7.1

**Comment by rainbeam** [comment]
Great :)

Have a look at #31 for a faster alternative to this (using a prebuilt docker image),

**Comment by rainbeam** [comment]
closing in favour of #31

**Pull request closed without merging**
